### ISSUE TITLE
The docs don't build with numpy 2.0

### ISSUE THREAD

**Issue by martinburchell** [RudolfCardinal/pythonlib#21]
I pinned NumPy to 2.0 in d56e383132727b1ce536ab7a217aad358ec2d984 because of this error when building the docs:
```

Warning, treated as error:
autodoc: failed to import module 'treatment_resistant_depression' from module 'cardinal_pythonlib.psychiatry'; the following exception was raised:
cannot import name 'NaN' from 'numpy' (/home/runner/venv/lib/python3.10/site-packages/numpy/__init__.py)
make: *** [Makefile:20: html] Error 2
The name of the builder is: htmlDeleting directory '/home/runner/work/pythonlib/pythonlib/docs/build/html'
Making HTML version of documentation
Traceback (most recent call last):
  File "/home/runner/work/pythonlib/pythonlib/docs/./rebuild_docs.py", line 62, in <module>
    subprocess.check_call(cmdargs)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'html', 'SPHINXOPTS="-W"']' returned non-zero exit status 2.
```

**Comment by RudolfCardinal** [comment]
Was going to update, but ``numpy==2.0.0`` is quite new and not yet supported by ``scipy`` (https://docs.scipy.org/doc/scipy/dev/toolchain.html). Not sure about ``numba``. When the time comes, helpful guide at https://numpy.org/devdocs/numpy_2_0_migration_guide.html.
